//console.log(ceres.S.isEmpty('1234'));
//console.log(ceres.S.truncate('Hello world', 5));
//console.log(ceres.S.join({a:1,b:2}, '=', ','));
//console.log(ceres.S.trim("a      "));
//console.log(ceres.S.stripTags('a <a href="#">link</a>'));
//console.log(ceres.S.escapeHtml('<div>Blah blah blah</div>'));
//console.log(ceres.S.unescapeHtml('&lt;div&gt;Blah blah blah&lt;/div&gt;'));
//console.log(ceres.S.toArray("123"));
//console.log(ceres.S.succ('abcd'));
//console.log(ceres.S.camelize('a_bcd'));
//console.log(ceres.S.camelize('ab-cd'));
//console.log(ceres.S.underscored('MOZTransform'));
//console.log(ceres.S.include('test', 'es'));
//console.log(ceres.S.startsWith('test', 'te'));
//console.log(ceres.S.strToNumber('100'));
//console.log(ceres.S.endsWith("test string", "ins"));
//console.log(ceres.S.toElement("test"));
//console.log("test".slice(-4));
//console.log(ceres.S.lpad("1", 8, "0"));
